### ISSUE TITLE
IllegalStateException: Fragment ServerFragment is not currently in the FragmentManager

### ISSUE THREAD

**Issue by avuton** [avuton/controldlna#1]
This can occur on startup.

<pre><code>05-22 13:36:10.404 27487-27487/com.github.nutomic.controldlna E/FragmentManager: Fragment ServerFragment{c517417} is not currently in the FragmentManager
05-22 13:36:10.404 27487-27487/com.github.nutomic.controldlna E/FragmentManager: Activity state:
05-22 13:36:10.404 27487-27487/com.github.nutomic.controldlna D/FragmentManager:   Local FragmentActivity 4ca9096 State:
05-22 13:36:10.404 27487-27487/com.github.nutomic.controldlna D/FragmentManager:     mCreated=truemResumed=false mStopped=false mReallyStopped=false
05-22 13:36:10.404 27487-27487/com.github.nutomic.controldlna D/FragmentManager:     mLoadersStarted=true
05-22 13:36:10.404 27487-27487/com.github.nutomic.controldlna D/FragmentManager:   FragmentManager misc state:
05-22 13:36:10.404 27487-27487/com.github.nutomic.controldlna D/FragmentManager:     mHost=android.support.v4.app.FragmentActivity$HostCallbacks@d7a004
05-22 13:36:10.404 27487-27487/com.github.nutomic.controldlna D/FragmentManager:     mContainer=android.support.v4.app.FragmentActivity$HostCallbacks@d7a004
05-22 13:36:10.404 27487-27487/com.github.nutomic.controldlna D/FragmentManager:     mCurState=4 mStateSaved=true mDestroyed=false
05-22 13:36:10.404 27487-27487/com.github.nutomic.controldlna D/FragmentManager:   View Hierarchy:
05-22 13:36:10.405 27487-27487/com.github.nutomic.controldlna D/FragmentManager:     com.android.internal.policy.PhoneWindow$DecorView{5a889ed V.E..... ... 0,0-0,0}
05-22 13:36:10.405 27487-27487/com.github.nutomic.controldlna D/FragmentManager:       android.widget.LinearLayout{d172022 V.E..... ... 0,0-0,0}
05-22 13:36:10.405 27487-27487/com.github.nutomic.controldlna D/FragmentManager:         android.view.ViewStub{aef3ab3 G.E..... ... 0,0-0,0 #10203ab android:id/action_mode_bar_stub}
05-22 13:36:10.405 27487-27487/com.github.nutomic.controldlna D/FragmentManager:         android.widget.FrameLayout{530b870 V.E..... ... 0,0-0,0}
05-22 13:36:10.405 27487-27487/com.github.nutomic.controldlna D/FragmentManager:           android.support.v7.widget.ActionBarOverlayLayout{490d7e9 V.E..... ... 0,0-0,0 #7f0e003f app:id/decor_content_parent}
05-22 13:36:10.405 27487-27487/com.github.nutomic.controldlna D/FragmentManager:             android.support.v7.widget.ContentFrameLayout{aab1c6e V.E..... ... 0,0-0,0 #1020002 android:id/content}
05-22 13:36:10.405 27487-27487/com.github.nutomic.controldlna D/FragmentManager:               android.support.v4.view.ViewPager{898cf0f VFED.... ... 0,0-0,0 #7f0e0050 app:id/pager}
05-22 13:36:10.405 27487-27487/com.github.nutomic.controldlna D/FragmentManager:             android.support.v7.widget.ActionBarContainer{cc0eb9c V.ED.... ... 0,0-0,0 #7f0e0040 app:id/action_bar_container}
05-22 13:36:10.405 27487-27487/com.github.nutomic.controldlna D/FragmentManager:               android.support.v7.widget.Toolbar{c9609a5 V.E..... ... 0,0-0,0 #7f0e0041 app:id/action_bar}
05-22 13:36:10.405 27487-27487/com.github.nutomic.controldlna D/FragmentManager:                 android.widget.TextView{d70917a V.ED.... ... 0,0-0,0}
05-22 13:36:10.406 27487-27487/com.github.nutomic.controldlna D/FragmentManager:               android.support.v7.widget.ActionBarContextView{39d4d2b G.E..... ... 0,0-0,0 #7f0e0042 app:id/action_context_bar}
05-22 13:36:10.406 27487-27487/com.github.nutomic.controldlna D/FragmentManager:               android.support.v7.widget.ScrollingTabContainerView{1bf2588 VFED.... ... 0,0-0,0}
05-22 13:36:10.406 27487-27487/com.github.nutomic.controldlna D/FragmentManager:                 android.support.v7.widget.LinearLayoutCompat{b029b21 V.ED.... ... 0,0-0,0}
05-22 13:36:10.406 27487-27487/com.github.nutomic.controldlna D/FragmentManager:                   android.support.v7.widget.ScrollingTabContainerView$TabView{7e64b46 VFE...C. .S. 0,0-0,0}
05-22 13:36:10.406 27487-27487/com.github.nutomic.controldlna D/FragmentManager:                     android.support.v7.widget.AppCompatTextView{6219107 V.ED.... .S. 0,0-0,0}
05-22 13:36:10.406 27487-27487/com.github.nutomic.controldlna D/FragmentManager:                   android.support.v7.widget.ScrollingTabContainerView$TabView{8e51234 VFE...C. ... 0,0-0,0}
05-22 13:36:10.406 27487-27487/com.github.nutomic.controldlna D/FragmentManager:                     android.support.v7.widget.AppCompatTextView{d4cc85d V.ED.... ... 0,0-0,0}
05-22 13:36:10.410 27487-27487/com.github.nutomic.controldlna D/AndroidRuntime: Shutting down VM
05-22 13:36:10.411 27487-27487/com.github.nutomic.controldlna E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.github.nutomic.controldlna, PID: 27487
                                                                                java.lang.IllegalStateException: Fragment ServerFragment{c517417} is not currently in the FragmentManager
                                                                                    at android.support.v4.app.FragmentManagerImpl.putFragment(FragmentManager.java:655)
                                                                                    at com.github.nutomic.controldlna.gui.MainActivity.onSaveInstanceState(MainActivity.java:242)
                                                                                    at android.app.Activity.performSaveInstanceState(Activity.java:1302)
                                                                                    at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1289)
                                                                                    at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4088)
                                                                                    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3490)
                                                                                    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3550)
                                                                                    at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-22 13:36:45.254 28378-28378/com.github.nutomic.controldlna W/System: ClassLoader referenced unknown path: /data/app/com.github.nutomic.controldlna-2</pre></code>

**Comment by avuton** [comment]
Fixed via 8a2145c.
